# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Admin_CPU\Desktop\Сode\1\Poliur\new_hollyday.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_w_hday_n(object):
    def setupUi(self, w_hday_n):
        w_hday_n.setObjectName("w_hday_n")
        w_hday_n.resize(355, 172)
        self.verticalLayout = QtWidgets.QVBoxLayout(w_hday_n)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_date = QtWidgets.QHBoxLayout()
        self.layout_date.setObjectName("layout_date")
        self.label_date = QtWidgets.QLabel(w_hday_n)
        self.label_date.setObjectName("label_date")
        self.layout_date.addWidget(self.label_date)
        self.dateedit = QtWidgets.QDateEdit(w_hday_n)
        self.dateedit.setObjectName("dateedit")
        self.layout_date.addWidget(self.dateedit)
        self.verticalLayout.addLayout(self.layout_date)
        self.layout_name = QtWidgets.QHBoxLayout()
        self.layout_name.setObjectName("layout_name")
        self.label_name = QtWidgets.QLabel(w_hday_n)
        self.label_name.setObjectName("label_name")
        self.layout_name.addWidget(self.label_name)
        self.lineedit = QtWidgets.QLineEdit(w_hday_n)
        self.lineedit.setObjectName("lineedit")
        self.layout_name.addWidget(self.lineedit)
        self.verticalLayout.addLayout(self.layout_name)
        self.layout_button = QtWidgets.QHBoxLayout()
        self.layout_button.setObjectName("layout_button")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_button.addItem(spacerItem)
        self.pushbutton_save = QtWidgets.QPushButton(w_hday_n)
        self.pushbutton_save.setObjectName("pushbutton_save")
        self.layout_button.addWidget(self.pushbutton_save)
        self.pushbutton_cancel = QtWidgets.QPushButton(w_hday_n)
        self.pushbutton_cancel.setObjectName("pushbutton_cancel")
        self.layout_button.addWidget(self.pushbutton_cancel)
        self.verticalLayout.addLayout(self.layout_button)

        self.retranslateUi(w_hday_n)
        QtCore.QMetaObject.connectSlotsByName(w_hday_n)

    def retranslateUi(self, w_hday_n):
        _translate = QtCore.QCoreApplication.translate
        w_hday_n.setWindowTitle(_translate("w_hday_n", "Выходной"))
        self.label_date.setText(_translate("w_hday_n", "Дата"))
        self.label_name.setText(_translate("w_hday_n", "Наименовани/описание"))
        self.pushbutton_save.setText(_translate("w_hday_n", "Сохранить"))
        self.pushbutton_cancel.setText(_translate("w_hday_n", "Отменить"))
