# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\GitHub\Poliur\Ui\alert\dialog_usave.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_unsave(object):
    def setupUi(self, Dialog_unsave):
        Dialog_unsave.setObjectName("Dialog_unsave")
        Dialog_unsave.resize(260, 138)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_unsave)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_unsave)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog_unsave)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog_unsave)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_unsave)
        QtCore.QMetaObject.connectSlotsByName(Dialog_unsave)

    def retranslateUi(self, Dialog_unsave):
        _translate = QtCore.QCoreApplication.translate
        Dialog_unsave.setWindowTitle(_translate("Dialog_unsave", "Подтвеждение"))
        self.label.setText(_translate("Dialog_unsave", "Закрыть не сохраняя?"))
        self.pushButton_cancel.setText(_translate("Dialog_unsave", "Да"))
        self.pushButton_2.setText(_translate("Dialog_unsave", "Отмена"))
