# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\GitHub\Poliur\Ui\alert\dialog_accord.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_accord(object):
    def setupUi(self, Dialog_accord):
        Dialog_accord.setObjectName("Dialog_accord")
        Dialog_accord.resize(379, 125)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_accord)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_accord)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_ok = QtWidgets.QPushButton(Dialog_accord)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_ok.setFont(font)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog_accord)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_accord)
        QtCore.QMetaObject.connectSlotsByName(Dialog_accord)

    def retranslateUi(self, Dialog_accord):
        _translate = QtCore.QCoreApplication.translate
        Dialog_accord.setWindowTitle(_translate("Dialog_accord", "Подтвеждение"))
        self.label.setText(_translate("Dialog_accord", "Подтверждаете действие?"))
        self.pushButton_ok.setText(_translate("Dialog_accord", "Да"))
        self.pushButton_cancel.setText(_translate("Dialog_accord", "Отмена"))
