# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\GitHub\Poliur\Ui\alert\dialog_delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_delete(object):
    def setupUi(self, Dialog_delete):
        Dialog_delete.setObjectName("Dialog_delete")
        Dialog_delete.resize(528, 149)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_delete)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog_delete)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tableWidget = QtWidgets.QTableWidget(Dialog_delete)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_ok = QtWidgets.QPushButton(Dialog_delete)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_ok.setFont(font)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog_delete)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_delete)
        QtCore.QMetaObject.connectSlotsByName(Dialog_delete)

    def retranslateUi(self, Dialog_delete):
        _translate = QtCore.QCoreApplication.translate
        Dialog_delete.setWindowTitle(_translate("Dialog_delete", "Удаление"))
        self.label.setText(_translate("Dialog_delete", "Подтвердите удаление записи:"))
        self.pushButton_ok.setText(_translate("Dialog_delete", "Подтверждаю"))
        self.pushButton_cancel.setText(_translate("Dialog_delete", "Отмена"))
