# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\GitHub\Poliur\Ui\dialog\ceh_plus_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_w_ceh_plus(object):
    def setupUi(self, w_ceh_plus):
        w_ceh_plus.setObjectName("w_ceh_plus")
        w_ceh_plus.resize(308, 74)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(w_ceh_plus)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.layout_data = QtWidgets.QHBoxLayout()
        self.layout_data.setObjectName("layout_data")
        self.label = QtWidgets.QLabel(w_ceh_plus)
        self.label.setObjectName("label")
        self.layout_data.addWidget(self.label)
        self.lineedit = QtWidgets.QLineEdit(w_ceh_plus)
        self.lineedit.setObjectName("lineedit")
        self.layout_data.addWidget(self.lineedit)
        self.horizontalLayout_2.addLayout(self.layout_data)
        self.layout_button = QtWidgets.QVBoxLayout()
        self.layout_button.setObjectName("layout_button")
        self.pushbutton_ok = QtWidgets.QPushButton(w_ceh_plus)
        self.pushbutton_ok.setObjectName("pushbutton_ok")
        self.layout_button.addWidget(self.pushbutton_ok)
        self.pushbutton_cancel = QtWidgets.QPushButton(w_ceh_plus)
        self.pushbutton_cancel.setObjectName("pushbutton_cancel")
        self.layout_button.addWidget(self.pushbutton_cancel)
        self.horizontalLayout_2.addLayout(self.layout_button)

        self.retranslateUi(w_ceh_plus)
        QtCore.QMetaObject.connectSlotsByName(w_ceh_plus)

    def retranslateUi(self, w_ceh_plus):
        _translate = QtCore.QCoreApplication.translate
        w_ceh_plus.setWindowTitle(_translate("w_ceh_plus", "Запись"))
        self.label.setText(_translate("w_ceh_plus", "Изготовлено"))
        self.pushbutton_ok.setText(_translate("w_ceh_plus", "Сохранить"))
        self.pushbutton_cancel.setText(_translate("w_ceh_plus", "Отменить"))
