# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\GitHub\Poliur\Ui\dialog\hollyday.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_w_hday(object):
    def setupUi(self, w_hday):
        w_hday.setObjectName("w_hday")
        w_hday.resize(714, 767)
        self.table = QtWidgets.QTableWidget(w_hday)
        self.table.setGeometry(QtCore.QRect(0, 0, 551, 761))
        self.table.setObjectName("table")
        self.table.setColumnCount(2)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        self.layoutWidget = QtWidgets.QWidget(w_hday)
        self.layoutWidget.setGeometry(QtCore.QRect(580, 20, 77, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_new = QtWidgets.QPushButton(self.layoutWidget)
        self.button_new.setObjectName("button_new")
        self.verticalLayout.addWidget(self.button_new)
        self.button_exit = QtWidgets.QPushButton(self.layoutWidget)
        self.button_exit.setObjectName("button_exit")
        self.verticalLayout.addWidget(self.button_exit)

        self.retranslateUi(w_hday)
        QtCore.QMetaObject.connectSlotsByName(w_hday)

    def retranslateUi(self, w_hday):
        _translate = QtCore.QCoreApplication.translate
        w_hday.setWindowTitle(_translate("w_hday", "Выходные"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("w_hday", "Дата"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("w_hday", "Наименование"))
        self.button_new.setText(_translate("w_hday", "Добавить"))
        self.button_exit.setText(_translate("w_hday", "Закрыть"))
