# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\GitHub\Poliur\Ui\dialog\new_hour.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_w_hour_n(object):
    def setupUi(self, w_hour_n):
        w_hour_n.setObjectName("w_hour_n")
        w_hour_n.resize(221, 285)
        self.verticalLayout = QtWidgets.QVBoxLayout(w_hour_n)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_date = QtWidgets.QHBoxLayout()
        self.layout_date.setObjectName("layout_date")
        self.label_date = QtWidgets.QLabel(w_hour_n)
        self.label_date.setObjectName("label_date")
        self.layout_date.addWidget(self.label_date)
        self.dateedit = QtWidgets.QDateEdit(w_hour_n)
        self.dateedit.setObjectName("dateedit")
        self.layout_date.addWidget(self.dateedit)
        self.verticalLayout.addLayout(self.layout_date)
        self.table = QtWidgets.QTableWidget(w_hour_n)
        self.table.setObjectName("table")
        self.table.setColumnCount(2)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        self.verticalLayout.addWidget(self.table)
        self.layout_button = QtWidgets.QHBoxLayout()
        self.layout_button.setObjectName("layout_button")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_button.addItem(spacerItem)
        self.pushbutton_save = QtWidgets.QPushButton(w_hour_n)
        self.pushbutton_save.setObjectName("pushbutton_save")
        self.layout_button.addWidget(self.pushbutton_save)
        self.pushbutton_cancel = QtWidgets.QPushButton(w_hour_n)
        self.pushbutton_cancel.setObjectName("pushbutton_cancel")
        self.layout_button.addWidget(self.pushbutton_cancel)
        self.verticalLayout.addLayout(self.layout_button)

        self.retranslateUi(w_hour_n)
        QtCore.QMetaObject.connectSlotsByName(w_hour_n)

    def retranslateUi(self, w_hour_n):
        _translate = QtCore.QCoreApplication.translate
        w_hour_n.setWindowTitle(_translate("w_hour_n", "Часы"))
        self.label_date.setText(_translate("w_hour_n", "Дата"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("w_hour_n", "Сотрудник"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("w_hour_n", "Часы"))
        self.pushbutton_save.setText(_translate("w_hour_n", "Сохранить"))
        self.pushbutton_cancel.setText(_translate("w_hour_n", "Отменить"))
