# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Documents\GitHub\Poliur\Ui\dialog\new_conteragent.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_w_agent(object):
    def setupUi(self, w_agent):
        w_agent.setObjectName("w_agent")
        w_agent.resize(571, 290)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(w_agent)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_date = QtWidgets.QHBoxLayout()
        self.layout_date.setObjectName("layout_date")
        self.layout_left = QtWidgets.QGridLayout()
        self.layout_left.setObjectName("layout_left")
        self.label_name = QtWidgets.QLabel(w_agent)
        self.label_name.setObjectName("label_name")
        self.layout_left.addWidget(self.label_name, 0, 0, 1, 1)
        self.lineedit_name = QtWidgets.QLineEdit(w_agent)
        self.lineedit_name.setObjectName("lineedit_name")
        self.layout_left.addWidget(self.lineedit_name, 0, 1, 1, 1)
        self.label_nicname = QtWidgets.QLabel(w_agent)
        self.label_nicname.setObjectName("label_nicname")
        self.layout_left.addWidget(self.label_nicname, 1, 0, 1, 1)
        self.lineedit_nicname = QtWidgets.QLineEdit(w_agent)
        self.lineedit_nicname.setObjectName("lineedit_nicname")
        self.layout_left.addWidget(self.lineedit_nicname, 1, 1, 1, 1)
        self.label_stat = QtWidgets.QLabel(w_agent)
        self.label_stat.setObjectName("label_stat")
        self.layout_left.addWidget(self.label_stat, 2, 0, 1, 1)
        self.lineedit_stat = QtWidgets.QLineEdit(w_agent)
        self.lineedit_stat.setObjectName("lineedit_stat")
        self.layout_left.addWidget(self.lineedit_stat, 2, 1, 1, 1)
        self.label_tel = QtWidgets.QLabel(w_agent)
        self.label_tel.setObjectName("label_tel")
        self.layout_left.addWidget(self.label_tel, 3, 0, 1, 1)
        self.lineedit_tel = QtWidgets.QLineEdit(w_agent)
        self.lineedit_tel.setObjectName("lineedit_tel")
        self.layout_left.addWidget(self.lineedit_tel, 3, 1, 1, 1)
        self.label_mail = QtWidgets.QLabel(w_agent)
        self.label_mail.setObjectName("label_mail")
        self.layout_left.addWidget(self.label_mail, 4, 0, 1, 1)
        self.lineedit_mail = QtWidgets.QLineEdit(w_agent)
        self.lineedit_mail.setObjectName("lineedit_mail")
        self.layout_left.addWidget(self.lineedit_mail, 4, 1, 1, 1)
        self.layout_date.addLayout(self.layout_left)
        self.layout_text = QtWidgets.QVBoxLayout()
        self.layout_text.setObjectName("layout_text")
        self.label_text = QtWidgets.QLabel(w_agent)
        self.label_text.setObjectName("label_text")
        self.layout_text.addWidget(self.label_text)
        self.listview_text = QtWidgets.QListView(w_agent)
        self.listview_text.setObjectName("listview_text")
        self.layout_text.addWidget(self.listview_text)
        self.layout_date.addLayout(self.layout_text)
        self.verticalLayout_2.addLayout(self.layout_date)
        self.layout_button = QtWidgets.QHBoxLayout()
        self.layout_button.setObjectName("layout_button")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_button.addItem(spacerItem)
        self.pushbutton_save = QtWidgets.QPushButton(w_agent)
        self.pushbutton_save.setObjectName("pushbutton_save")
        self.layout_button.addWidget(self.pushbutton_save)
        self.pushbutton_cancel = QtWidgets.QPushButton(w_agent)
        self.pushbutton_cancel.setObjectName("pushbutton_cancel")
        self.layout_button.addWidget(self.pushbutton_cancel)
        self.verticalLayout_2.addLayout(self.layout_button)

        self.retranslateUi(w_agent)
        QtCore.QMetaObject.connectSlotsByName(w_agent)

    def retranslateUi(self, w_agent):
        _translate = QtCore.QCoreApplication.translate
        w_agent.setWindowTitle(_translate("w_agent", "Карточка контрагента"))
        self.label_name.setText(_translate("w_agent", "Наименование контрагента"))
        self.label_nicname.setText(_translate("w_agent", "Сокращение"))
        self.label_stat.setText(_translate("w_agent", "Статус"))
        self.label_tel.setText(_translate("w_agent", "Телефон"))
        self.label_mail.setText(_translate("w_agent", "Электронная почта"))
        self.label_text.setText(_translate("w_agent", "Дополнительная информация"))
        self.pushbutton_save.setText(_translate("w_agent", "Сохранить"))
        self.pushbutton_cancel.setText(_translate("w_agent", "Отменить"))
