# Generated by Django 4.2.1 on 2023-05-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nicname', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=9, null=True)),
                ('tnum', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'agent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_sm', models.IntegerField()),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('id_plane', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'balance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupSm',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'group_sm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hardness',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'hardness',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hollyday',
            fields=[
                ('id_date', models.DateField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'hollyday',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField()),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('sum', models.IntegerField()),
                ('ship_num', models.TextField()),
                ('text', models.CharField(blank=True, max_length=150, null=True)),
                ('id_ship_agent', models.ForeignKey(blank=True, db_column='id_ship_agent', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.agent')),
            ],
            options={
                'db_table': 'shipment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'source',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stat_ship',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'teg',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'test1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_name', models.CharField(blank=True, max_length=20, null=True)),
                ('foto_name', models.CharField(blank=True, max_length=20, null=True)),
                ('tnum', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.IntegerField()),
                ('bonus', models.SmallIntegerField()),
                ('date_in', models.DateField(blank=True, null=True)),
                ('data_out', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('date_work', models.ForeignKey(db_column='date_work', on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.hollyday')),
                ('id_workers', models.ForeignKey(blank=True, db_column='id_workers', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.workers')),
            ],
            options={
                'db_table': 'work_hours',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TegsNom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nom', models.ForeignKey(db_column='id_nom', on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.balance')),
                ('id_teg', models.ForeignKey(db_column='id_teg', on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.teg')),
            ],
            options={
                'db_table': 'tegs_nom',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SumShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bal', models.ForeignKey(blank=True, db_column='id_bal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.balance')),
                ('id_ship', models.ForeignKey(blank=True, db_column='id_ship', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.shipment')),
            ],
            options={
                'db_table': 'sum_ship',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('id_group', models.ForeignKey(db_column='id_group', on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.groupsm')),
            ],
            options={
                'db_table': 'subgroup',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='id_stat',
            field=models.ForeignKey(blank=True, db_column='id_stat', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.statship'),
        ),
        migrations.CreateModel(
            name='OrderSm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('priority', models.SmallIntegerField()),
                ('text', models.CharField(blank=True, max_length=150, null=True)),
                ('id_agent', models.ForeignKey(db_column='id_agent', on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.agent')),
            ],
            options={
                'db_table': 'order_sm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nicname', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=150, null=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('id_form', models.PositiveIntegerField(blank=True, null=True)),
                ('id_subgroup', models.ForeignKey(db_column='id_subgroup', on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.subgroup')),
            ],
            options={
                'db_table': 'nomenclature',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='balance',
            name='id_hardness',
            field=models.ForeignKey(blank=True, db_column='id_hardness', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.hardness'),
        ),
        migrations.AddField(
            model_name='balance',
            name='id_nomenclature',
            field=models.ForeignKey(db_column='id_nomenclature', on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.nomenclature'),
        ),
        migrations.AddField(
            model_name='balance',
            name='id_order',
            field=models.ForeignKey(blank=True, db_column='id_order', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.ordersm'),
        ),
        migrations.AddField(
            model_name='balance',
            name='id_source',
            field=models.ForeignKey(db_column='id_source', on_delete=django.db.models.deletion.DO_NOTHING, to='poli_1.source'),
        ),
    ]
